import "./globals.css"
import ThemeProvider from "../components/theme-provider.jsx"
import Header from "@/components/header"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`bg-linear-to-br from-gray-950 via-zinc-900 to-stone-900`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
         {/*header*/}
          <Header />

          
          <main className="min-h-screen relative container mx-auto pt-40 md:pt-32">
            {/* glow */}
            <div className="pointer-events-none absolute inset-0 -z-10 overflow-hidden">
                <div className="absolute top-0 left-1/4 w-96 h-96 bg-pink-600/20 rounded-full blur-3xl"></div>
                <div className="absolute bottom-0 right-1/4 w-96 h-96 bg-orange-600/20 rounded-full blur-3xl"></div>
            </div>
            <div className="relative z-10 min-h-[80vh]">{children}</div>

            {/*Footer */}
            <footer className="border-tborder-gray-800/50 py-8 px-6 max-w-7xl mx-auto">
                      <div className="text-sm text-gray-400"> made with love kndg</div>
            </footer>
          </main>
        </ThemeProvider>
      </body>
    </html>
  )
}
